site_name: Hutch Bot Docs
# site_url: https://marzaelise.github.io/hutch-bot-docs
site_url: http://127.0.0.1:8000
site_description : Official documentation for Hutch Bot
site_author : Marcus
copyright: Marcus

repo_url: https://github.com/MarzaElise/Hutch-Bot/
repo_name: Hutch Bot

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - python
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
    palette:
        primary: red
        scheme: slate
    icon:
        # logo: octicons/repo-24 # a repo pic to represent docs --------------| Me Making Decisicions
        logo: octicons/rocket-24 # or a nice rocket pic ----------------------| be like

plugins:
    - search
    - redirects:
        redirect_maps:
            'index.md': 'home/index.md'
            'support.md': 'https://discord.gg/NVHJcGdWBC'
            'invite.md': 'https://dsc.gg/hutch-bot'
            'contact.md': 'https://discord.com/users/754557382708822137'

nav:
    - Home:
        - Welcome: home/index.md
        - Features:
            - Auto Moderation: features/auto-mod.md
        - Commands:
            - Fun: commands/fun.md
            - Moderation: commands/moderation.md
            - Miscellaneous: commands/misc.md
            - Developer: commands/dev.md
        - Extra:
            - Support: support.md
            - Upcoming: upcoming/index.md
            - Invite: invite.md
    - Commands:
        - Fun: commands/fun.md
        - Moderation: commands/moderation.md
        - Miscellaneous: commands/misc.md
        - Developer: commands/dev.md
    - Upcoming: 
        - upcoming/index.md
    - Support:
        - support.md
    - Invite:
        - invite.md
    - Contact: 
        - contact.md

markdown_extensions:

    - meta
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets
    - abbr
    - def_list

    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: true

extra:
  homepage: https://example.com
