site_name: Hutch Bot Docs
# site_url: https://hutch-bot.readthedocs.io/en/latest
site_url: http://127.0.0.1:8000 # for development
site_description : 'Official documentation for Hutch Bot'
site_author : Marcus
copyright: 'Copyright &copy; 2021 - present Marcus'

repo_url: https://github.com/MarzaElise/Hutch-Bot/
repo_name: Hutch Bot

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - python
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
    palette:
        primary: red
        scheme: slate
    icon:
        repo: fontawesome/brands/github
        # logo: octicons/repo-24 # a repo pic to represent docs =============|    Took 50m to 
        logo: octicons/rocket-24 # or a nice rocket pic =====================| -> choose which
#                                                                            |    one to use
plugins:
    - git-revision-date
    - search
    - redirects:
        redirect_maps:
            'index.md': 'home/index.md'
            'redirects/support.md': 'https://discord.gg/NVHJcGdWBC'
            'redirects/invite.md': 'https://dsc.gg/hutch-bot'
            'redirects/contact.md': 'https://discord.com/users/754557382708822137'

nav:
    - Home:
        - Welcome: home/index.md
        - Features:
            - Auto Moderation: features/auto-mod.md
        - Commands:
            - Fun: commands/fun.md
            - Moderation: commands/moderation.md
            - Miscellaneous: commands/misc.md
            - Developer: commands/dev.md
        - Extra:
            - Support: redirects/support.md
            - What's New: whats-new/index.md
            - Invite: redirects/invite.md
            - Contact: redirects/contact.md
    - Commands:
        - Fun: commands/fun.md
        - Moderation: commands/moderation.md
        - Miscellaneous: commands/misc.md
        - Developer: commands/dev.md
    - What's New: 
        - whats-new/index.md
    - Support:
        - redirects/support.md
    - Invite:
        - redirects/invite.md
    - Contact: 
        - redirects/contact.md

markdown_extensions:

    - meta
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets
    - abbr
    - def_list

    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: true
